title: "Prototipagem em código para designers"
date-modified: last-modified
author:
  - name: Ana Fernandes Rodrigues
    url: https://www.anarodrigues.design

project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    favicon: favicon.ico
    lang: pt
    date-format: "MMMM [de] YYYY"
    language:
      title-block-author-single: "Curso desenhado por"
      title-block-modified: "Última actualização"




